### ISSUE TITLE
中間進捗報告ができる

### ISSUE THREAD

**Issue by AquiTCD** [challenge-every-month/cem-app#21]
## 要望概要
中間進捗報告もできるようになる

### その要望を満たすと嬉しいこと
+ 自身で発表した挑戦目標をコピペして整形しなくてよい
+ 仕組みがあることで進捗発表の障壁を下げる

## ゴール
+ [ ] `/cem_progress` などでダイアログを開く
+ [ ] 目標一つづつにコメントをつけることができる
+ [ ] コメントはDBに保存される
+ [ ] 記入した結果をメッセージとして表示できる

**Comment by AquiTCD** [comment]
進捗度は段階評価とかにすると良いかもしれない。
未着手、進捗半分以下、進捗半分以上、完了済
ぐらいの粒度。

**Comment by hirotoKirimaru** [comment]
以下の前提で考慮。
- 進捗はDBに保存しない
- チャレンジとコメントは常に1:1。
- 振り返りは何度もできる。

![cemProgressのステートマシン図](https://user-images.githubusercontent.com/30658134/79760165-a498e400-835a-11ea-9acd-d972e95d9c88.png)
![チャレンジ一つ一つに紐づくコメント](https://user-images.githubusercontent.com/30658134/79760184-a95d9800-835a-11ea-9db7-98f25ee91cfd.png)
