### ISSUE TITLE
登録されたプロジェクトとチャレンジの修正、変更

### ISSUE THREAD

**Issue by AquiTCD** [challenge-every-month/cem-app#8]
## 要望概要
既に登録された自分のプロジェクトとチャンレンジの修正、変更をするスラッシュコマンドが必要
なお、コマンドは`/cem_edit`を予定

### その要望を満たすと嬉しいこと
+ 間違えて登録したプロジェクトやチャレンジの変更ができる
+ 既に登録したが対象月の変更をしたり、内容の変更に対応できる
+ 結果、思いついたらどんどん登録ができるようになる

## ゴール
+ [ ] すでに登録したプロジェクトの一覧を選択できる
+ [ ] 選択したプロジェクトの月を変更できる
+ [ ] 選択したプロジェクトのチャレンジを変更できる

**Comment by AquiTCD** [comment]
既にpublish(表明）された挑戦の編集を
できる/できない
も議論したいですね。

**Comment by AquiTCD** [comment]
個人的には「できない」で良いかなと思っていまして、
理由は、当初の挑戦を変更する必要があった = 挑戦目標の立てかたが悪かった
と振り返れて次回からに活かせそう、という理由ですね。

ただし、人によってはとりあえずで目標立て進捗みながら調整していく方法もあると思うので、一概にこの方法が良いとは思っていません。

それも含めて、できる/できない を議論したいですね。
とりあえず「できる」に振って、僕と同じ考え方なら「しない」方法もありますし。

**Comment by hirotoKirimaru** [comment]
「できない」でいいと思います。

変更したくなったら、新しく目標を立てればいいですし、履歴として残す方式のほうが後々振り返りやすいかと思っています。
